### PR TITLE
message test case

### PR DESCRIPTION
**Pull request by Ellenhuang001**
add message test case

### CODE REVIEW

**Review by TejasRaghuvanshi — DISMISSED** [review]
looks good

**Review by an1381h — DISMISSED** [review]
Looked over the tests briefly, and they are good test cases.

**Review by han5z — CHANGES_REQUESTED** [review]
Try to add some tests for when the use case fails and the fail view is presented

**Review by aurorali17 — APPROVED** [review]

**Review by han5z — APPROVED** [review]
Test cases look good now, approving.

**Pull request merged**
