### PR TITLE
Reactions feature

### PR DESCRIPTION
**Pull request by han5z**

### CODE REVIEW

**Review by an1381h — APPROVED** [review]
Follows clean architecture and SOLID design principals as far as I could tell.

**Review by an1381h — APPROVED** [review]
Looks well done, and follows clean architecture there seems to be documentation from the last time I reviewed it which is very good. I do not see any SOLID design violations. Overall good work

**Review by ashleydewitte — DISMISSED** [review]

**Review by an1381h — APPROVED** [review]
Looks well done, and follows clean architecture there seems to be documentation from the last time I reviewed it which is very good. I do not see any SOLID design violations. Overall good work

**Review by ashleydewitte — APPROVED** [review]

**Review by an1381h — APPROVED** [review]
Looks well done, and follows clean architecture there seems to be documentation from the last time I reviewed it which is very good. I do not see any SOLID design violations. Overall good work

**Review by Kushagra-Raghuvanshi — APPROVED** [review]
Looks good. You can merge this with main

**Pull request merged**
